import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import '@fortawesome/fontawesome-free/css/all.min.css';

import { CartProvider } from "use-shopping-cart";


const inter = Inter({ subsets: ['latin'] })

 export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CartProvider
      // Enables local storage
      shouldPersist={true}
    >

       {children}
      </CartProvider>  
        </body>
    </html>
  )
}